script: "export DISPLAY=':313' && xvbf :313 -ac -screen 0 1024x768x8 && bundle exec rake db:drop db:create db:migrate spec cucumber && xvbf stop"
notifications:
  recipients:
    - parndt@gmail.com
    - ugis.ozolss@gmail.com
rvm:
  - 1.9.2
  - 1.8.7
  - rbx
  - rbx-2.0
  - ree
  - jruby