login: &login
  access_key_id: 
  secret_access_key: 

development:
  bucket_name: 
  <<: *login
  distribution_domain: 

test:
  bucket_name: 
  <<: *login
  distribution_domain: 

production:
  bucket_name: 
  <<: *login
  distribution_domain: 
